### PR TITLE
Fn fix

### PR DESCRIPTION
**Pull request by ShelbyZ**
Fixing function path to include absolute similar to issue #5 , but fixing will allow Functions to call other functions.

### CODE REVIEW

**Comment by dkundel** [comment]
Hi @ShelbyZ,

Thanks for fixing this. Can you address my one comment though so that we can make sure it works in Windows just as well? 🙂

Cheers,
Dominik

**Comment by ShelbyZ** [comment]
I'm not sure I was able to find the comment regarding working in Windows.  I'm currently running on a Window machine without issue.

**Comment by dkundel** [comment]
My bad. Forgot to publish the review 🤦‍♂️ Basically just switching to `path.join()`. It's interesting that it actually works in Windows, they might be doing some fixes inside Node.js but could be that people will use that path in a different way. So just to be safe.

**Comment by dkundel** [comment]
Thank you so much!

**Pull request merged**
